[package]
name = "yoinky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.15.1"
ratatui = { version = "0.26.0", features = ["crossterm"] }
crossterm = "0.27.0"
